train_config:
  project: imdb-cls
  group: bert-vs-modernbert
  run_name: modernbert
  epochs: 5
  lr: 5e-5
  seed: 42

model_config:
  pretrained_model_name: answerdotai/ModernBERT-base
  dropout: 0.1
  num_classes: 2

data_config:
  model_name: answerdotai/ModernBERT-base
  max_len: 128
  valid_size: 0.1
  split_seed: 42

  batch_size: 64
  num_workers: 2
  pin_memory: true
  drop_last: true
  persistent_workers: true
